In [1]:
import torch
print(torch.__version__)

2.10.0+cu128


In [2]:
if torch.cuda.is_available():
  print("gpu is available!")
  print(f"Using Gpu: {torch.cuda.get_device_name(0)}")
else:
  print('gpu not availabe. Using CPU.')

gpu is available!
Using Gpu: Tesla T4


#Creating Tensors

In [4]:
#using empty
a = torch.empty(2,3)

In [5]:
#check type
type(a)

torch.Tensor

In [7]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.rand(2,3)

tensor([[0.6298, 0.1165, 0.7276],
        [0.6819, 0.2402, 0.3054]])

In [10]:
# manual seed
torch.manual_seed(100)
torch.rand(3,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080]])

In [11]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
#other methods
print("using aragne ->", torch.arange(0,10,2))

#using linespace
print("Using linspace ->", torch.linspace(0,10,10))

#using eyw (identity matrix)
print('using eye ->', torch.eye(5))

#using full
print("using full ->", torch.full((3,3),5))

using aragne -> tensor([0, 2, 4, 6, 8])
Using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


#Tensor Shapes

In [14]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [16]:
x.shape

torch.Size([2, 3])

In [17]:
torch.empty_like(x)

tensor([[                  0, 7310593858020254331, 3616445622929465956],
        [6067810143170473270, 3617580409425639728, 6499595003662710574]])

In [18]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [28]:
torch.rand_like(x, dtype=torch.float32)
"""
Reason:
x has integers in the matrix where as rand generates floats between 0 and 1.
have to explictly tell the data type.
"""

'\nReason:\nx has integers in the matrix where as rand generates floats between 0 and 1.\nhave to explictly tell the data type.\n'

#Tensor Data Types

In [23]:
# find data type
x.dtype

torch.int64

In [24]:
#assign data type
torch.tensor([1.0,2.0,3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [25]:
torch.tensor([1,2,3], dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [26]:
#using .to
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

#Mathematical Operations

##Scaler Operations

In [29]:
x = torch.rand(3,3)

In [30]:
x + 2

x-2

x*2

x/3

(x*100)//3

#mod


tensor([[30., 33., 25.],
        [ 7., 10.,  5.],
        [27., 18., 32.]])

In [31]:
a = torch.rand(4,4)
b = torch.rand(4,4)

In [32]:
#add
a+b

#sub
a-b

#multiply
a*b

#division
a/b

#power
a**b

#mod
a%b



tensor([[0.4440, 0.0148, 0.0969, 0.1462],
        [0.2426, 0.1743, 0.0364, 0.2472],
        [0.7909, 0.4235, 0.0169, 0.2209],
        [0.0410, 0.0287, 0.1629, 0.3372]])

In [33]:
c = torch.tensor([1,-2,3,-4])

In [34]:
torch.abs(c)

tensor([1, 2, 3, 4])